---
- name: install nvm
  git:
    repo: https://github.com/creationix/nvm.git
    dest: /home/ec2-user/.nvm

- name: reload .nvm setting
  become_user: ec2-user
  shell: bash -lc "source ~/.nvm/nvm.sh"

- name: edit bashrc
  become: yes
  lineinfile:
    path: /home/ec2-user/.bash_profile
    line: "{{ item }}"
  with_items:
    - 'if [ -f ~/.nvm/nvm.sh ]; then'
    - '      . ~/.nvm/nvm.sh'
    - 'fi'

- name: reload nvm setting
  become_user: ec2-user
  shell: bash -lc "source ~/.bash_profile"

- name: edit permission nvm
  become: yes
  file:
    path: /home/ec2-user/.nvm
    state: directory
    owner: ec2-user
    group: ec2-user

- name: install nodejs
  become_user: ec2-user
  shell: bash -lc "nvm install {{ nodejs_version }}"

- name: install yarn
  become_user: ec2-user
  shell: bash -lc "npm install yarn -g"

